# Generated by Django 4.1.3 on 2023-01-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_images_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='created',
            new_name='created_date',
        ),
    ]
