# Generated by Django 4.1.3 on 2023-01-17 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variationmanager_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
