# Generated by Django 4.1.3 on 2023-02-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_shipment_charges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tax',
            new_name='shipment_charges',
        ),
    ]
